# Generated by Django 4.1.7 on 2023-04-01 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratingprofessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
